// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJnBxdXMmKrjSXGqJOJyvxODUGG_TJtPc',
    appId: '1:604541592319:web:e4e11cfc1390c275c0e2ca',
    messagingSenderId: '604541592319',
    projectId: 'students-clearence',
    authDomain: 'students-clearence.firebaseapp.com',
    storageBucket: 'students-clearence.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSgshBxBaijD1dPCViXXUl7Y5HyxADb1Y',
    appId: '1:604541592319:android:072b1129ba4a7f61c0e2ca',
    messagingSenderId: '604541592319',
    projectId: 'students-clearence',
    storageBucket: 'students-clearence.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcAOtzNUu1bK5QFN8ZRZyNp5FynyS_hGc',
    appId: '1:604541592319:ios:10568a148bae6f03c0e2ca',
    messagingSenderId: '604541592319',
    projectId: 'students-clearence',
    storageBucket: 'students-clearence.appspot.com',
    iosClientId: '604541592319-8s6rub48lid8m9gaqbi5pconjmrmmghd.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentClearance',
  );
}
